package com.a2.swifting_fitness.common.constants;

public class StringConstants {
    public static final String noUserFromThatUsername = "No email available in our system";
    public static final String fullNameRequired = "Please enter your full name";
    public static final String emailRequired = "Please enter your email";
    public static final String emailNotValid = "Email is invalid";
    public static final String ageRequired = "Please enter your age";
    public static final String ageNotValid = "Age must be between 18 to 100";
    public static final String genderRequired = "Please enter your gender";
    public static final String passwordRequired = "Please enter your password";
    public static final String otpRequired = "Please enter your OTP";
    public static final String passwordRegexMessage = "Password must have one upper case, one lower case, one symbol and one digit";
    public static final String passwordMinLengthMessage = "Password must be 8 character long";
    public static final String refreshTokenRequired = "Refresh token required.";
    public static final String registerSuccessfully = "Registered successfully. Please check OTP on your gmail to set your password.";
    public static final String reRegisterSuccessfully = "Re-Registered successfully. Check email for OTP, and this time please complete all registration steps.";
    public static final String reRegisterSuccessfullyReuseOTP = "Re-Registered successfully. Please reuse same OTP previously sent.";
    public static final String otpVerifiedSuccessfully = "OTP Verified successfully";
    public static final String passwordSetSuccessfully = "Account created and password set successfully";
    public static final String loggedInSuccessfully = "Logged in successfully";
    public static final String emailSentSuccessfully = "Email sent successfully";
    public static final String passwordChangedSuccessfullyPleaseLogin = "Password changed successfully. Please login and enjoy your fitness journey.";
    public static final String invalidCredentials = "Invalid Credentials";
    public static final String emailAlreadyExist = "User with given email already exist";
    public static final String blockingUserDueToWrongTrial = "Lots of wrong trial. Your account is blocked for 1 day";
    public static final String invalidOTP = "Invalid OTP";
    public static final String userLockedCannotContinue = "User account is locked due to suspicious requests. Please try again later.";
    public static final String sendingOTPLocked = "Lots of OTP sent. Please try again later after few hours.";
    public static final String newOTPCanOnlyBeSentAfter = "New OTP can only be sent after 1 minutes";
    public static final String userDetailsFetchedSuccessfully = "User details fetched successfully.";
    public static final String refreshTokenSuccessful = "Refresh Token Successful";
    public static final String userNotFound = "User not found...";
    public static final String invalidToken = "Invalid JWT Token. How the heck this was allowed in our system.";
    public static final String accountSetupNotComplete = "Your account setup isn't completed yet, due to which your account is currently disabled.";
    public static final String accountLocked = "Your account has been locked for few hours. It might be due to lots of wrong attempts.";
    public static final String invalidUsernamePassword = "Invalid username or password.";
    public static final String refreshTokenExpired = "Refresh token is expired. Please make a new login..!";
    public static final String invalidRefreshToken = "Invalid refresh token";
}
